# Generated by Django 5.2.4 on 2025-08-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('nick_name', models.CharField(blank=True, default='系统昵称', max_length=18, null=True, verbose_name='用户昵称')),
                ('_pwd', models.CharField(blank=True, max_length=32, null=True, verbose_name='真实密码')),
                ('gender', models.IntegerField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别')),
                ('introduction', models.TextField(blank=True, default='该用户很懒,什么介绍都没有', null=True, verbose_name='用户简介')),
                ('avatar', models.CharField(blank=True, max_length=50, null=True, verbose_name='头像')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
