# Generated by Django 5.2.4 on 2025-08-06 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cart', serialize=False, to='user_app.user', verbose_name='用户')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 't_carts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cart_app.category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 't_category',
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='商品价格')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('status', models.IntegerField(choices=[(0, '有货'), (1, '缺货')], default=0, verbose_name='存货状态')),
                ('stock', models.IntegerField(default=0, verbose_name='商品库存')),
                ('pic', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品图片')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='商品地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='cart_app.category', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 't_goods',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart_app.cart', verbose_name='购物车')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_app.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车商品',
                'verbose_name_plural': '购物车商品',
                'db_table': 't_cartitem',
                'unique_together': {('carts', 'goods')},
            },
        ),
    ]
