# Generated by Django 5.2.4 on 2025-09-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_remove_goods_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='badgeType',
            field=models.CharField(blank=True, choices=[(0, 'hot'), (1, '')], default=0, max_length=12, null=True, verbose_name='商品销售程度'),
        ),
    ]
