# Generated by Django 5.2.4 on 2025-10-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_goods_badgetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='badgeType',
            field=models.CharField(blank=True, choices=[(0, 'new'), (1, 'hot')], default='hot', max_length=12, null=True, verbose_name='商品销售程度'),
        ),
    ]
