"""
Django settings for django_one project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kw(u)3hnb97pj=4p&x0%ew2tc6rvlm76%wfjl8&+vwe5rynaor'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# ALLOWED_HOSTS = ['*'] 是针对主机名的设置，并不能解决 CORS 问题。跨域访问需要使用 CORS 中间件来配置相关权限，您仍然需要按照前面提到的步骤配置 CORS
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',# 自带的session
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders', # 跨域
    'user_app',# 用户模块
    'cart_app',# 购物车
    'banner_app', # 轮播图
    'address_app', # 地址
]
# SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 默认使用数据库存储
# SESSION_COOKIE_AGE = 300  # 会话默认 5 分钟过期

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 确保它在 CommonMiddleware 之前 跨域中间件
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_app.middleware.LoginRequiredMiddleware', # 验证是否登录中间件
]



# CORS_ALLOW_ALL_ORIGINS = True  # 开发环境中使用（不建议用于生产）

# 或者只允许特定的来源：
# 允许跨源资源共享的源列表，表示哪些外部域名可以访问此服务
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  # 允许 localhost:8000 访问
]
# 允许跨域请求时发送认证信息，例如 cookies 或 Authorization 头
CORS_ALLOW_CREDENTIALS = True  # 如果您使用认证令牌或 cookies

CORS_ALLOW_HEADERS = [
    'token',  # 或者你实际使用的 token 名称
    'content-type',
]
ROOT_URLCONF = 'django_one.urls'
import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_one.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':"xiaomishopper" ,
        'USER':'root',
        'PASSWORD':'root',
        'HOST':'127.0.0.1',
        'POST':3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# 这里我们将媒体文件放在 'media/' 文件夹中
# MEDIA_URL = '/media/'  # 访问媒体文件的 URL 前缀
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 媒体文件在本地存储的位置

# 静态文件的 URL 路径（访问静态文件的前缀）
STATIC_URL = '/static/'
# 存放静态文件的本地目录
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# 生产环境中收集静态文件的目标目录
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 生产环境中使用 collectstatic 收集静态文件
# python manage.py collectstatic

JWT_TOKEN_EXPIRE_TIME = 3600 * 24 *24 *24 # token有效时间 2小时
JWT_SECRET = 'abc'   # 加解密密钥
JWT_ALGORITHM = 'HS256'  # 加解密算法