# Generated by Django 5.2.4 on 2025-08-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=32, verbose_name='轮播图图片地址')),
                ('title', models.CharField(max_length=32, verbose_name='轮播标题')),
            ],
        ),
    ]
