# Generated by Django 5.2.4 on 2025-08-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='t_banner',
        ),
    ]
