# Generated by Django 5.2.4 on 2025-10-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('province', models.CharField(max_length=64, verbose_name='省份')),
                ('city', models.CharField(max_length=32, verbose_name='城市')),
                ('district', models.CharField(max_length=32, verbose_name='区县')),
                ('detail', models.CharField(max_length=32, verbose_name='具体地址')),
                ('isDefault', models.CharField(choices=[(0, 'false'), (1, 'true')], default=0, max_length=8, verbose_name='默认地址')),
            ],
            options={
                'db_table': 't_address',
            },
        ),
    ]
